user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  pass_rs:
    rs_sent_at: 2
users_helper:
  gravatar:
    size: 80
session:
  remember_me: "1"
views:
  users:
    _user:
      size: 50

per_page: 10
