user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  pass_rs:
    rs_sent_at: 2
users_helper:
  gravatar:
    size: 80
session:
  remember_me: "1"
views:
  users:
    _user:
      size: 50
  shared:
    _micropost:
      size_megabytes: 5
    _user_info:
      size: 50
per_page: 5
user_size: 50
picture_size: 5
content_size: 140
show_follow_size: 30
